name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
#          cache: maven
          cache: gradle
          java-version: '17'

      #      - name: Build with Maven
      #        run: mvn clean install
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and Generate Coverage Report
        run: ./gradlew clean verify

#      jacoco ìƒëµ
#      - name: Upload JaCoCo HTML Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: jacoco-report
#          path: target/site/jacoco
#
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: target/site/jacoco/jacoco.xml

      - name: Discord Notify Success
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          message: |
            âœ… CI ë¹Œë“œ ì„±ê³µ
            ğŸ”¨ ë¸Œëœì¹˜: `${{ github.ref_name }}`
            ğŸ§ª ì»¤ë°‹: `${{ github.event.head_commit.message }}`
            ğŸ§‘â€ğŸ’» ì‘ì„±ì: `${{ github.actor }}`
            ğŸ”— [ìì„¸íˆ ë³´ê¸°](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Discord Notify Failure
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          message: |
            âŒ CI ë¹Œë“œ ì‹¤íŒ¨
            ğŸ”¨ ë¸Œëœì¹˜: `${{ github.ref_name }}`
            ğŸ§ª ì»¤ë°‹: `${{ github.event.head_commit.message }}`
            ğŸ’¬ í™•ì¸ì´ í•„ìš”í•©ë‹ˆë‹¤!
            ğŸ”— [ë¡œê·¸ ë³´ê¸°](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
